echo "bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 1 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef1.sam" &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 1 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef1.sam &>> apr_28.log
echo "bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 5 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef5.sam" &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 5 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef5.sam &>> apr_28.log
echo "bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 10 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef10.sam" &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 10 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef10.sam &>> apr_28.log
echo "bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 20 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef20.sam" &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 20 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef20.sam &>> apr_28.log
echo "bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 30 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef30.sam" &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 30 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef30.sam &>> apr_28.log
echo "bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 40 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef40.sam" &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 40 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef40.sam &>> apr_28.log
bowtie2 -p 12 --very-sensitive --score-min L,-12,0 -k 1 -x ../volum2/Wheat_IWGSC_WGA_v1.0_pseudomolecules/bowtie2-index/new -U Breeding_Pop/tagForAlign.fa -S Breeding_Pop/paperRevision/tagForAlignReportNewRef1.sam &>> apr_28.log